-- 20 Story Seeds with diverse authors
INSERT INTO stories (id, title, content, author_name, story_type, tags, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000001', 'The Whispering Walls', 'The old house at the end of Maple Street had been abandoned for decades. But last night, Maya saw a light in the attic window — and heard her dead grandmother''s voice calling her name. Does she go inside?', 'Elena Voss', 'seed', ARRAY['Horror','Mystery'], 0, 34, 2),
('a0000001-0000-0000-0000-000000000002', 'The Last Train to Nowhere', 'The conductor punched a ticket that read "ONE WAY — NO RETURN." The train hummed with an energy that felt alive. Every passenger looked terrified except one old man, smiling. Where does the train go?', 'Marcus Chen', 'seed', ARRAY['Sci-Fi','Thriller'], 0, 67, 3),
('a0000001-0000-0000-0000-000000000003', 'Kingdom of Ash', 'The throne room smelled of burnt offerings and betrayal. Queen Sera held the crown — still warm from the dead king''s head — and looked at the army gathering beyond her walls. Surrender or fight?', 'Aria Blackwood', 'seed', ARRAY['Fantasy','Drama'], 0, 112, 5),
('a0000001-0000-0000-0000-000000000004', 'Signal from Titan', 'The radio burst from Saturn''s moon contained a single word in perfect English: "HELP." NASA had never sent anyone there. The message repeated every 11 minutes. Do we respond?', 'Dr. James Park', 'seed', ARRAY['Sci-Fi','Mystery'], 0, 89, 1),
('a0000001-0000-0000-0000-000000000005', 'The Memory Thief', 'She woke up in a hospital with no memory of who she was — but perfect memories of twelve other people''s lives. A nurse handed her a note in her own handwriting: "Trust no one. Especially yourself." What does she do first?', 'Lily Tanaka', 'seed', ARRAY['Thriller','Mystery'], 0, 156, 4),
('a0000001-0000-0000-0000-000000000006', 'The Deep Below', 'The submarine hit something at 4,000 meters — something that hit back. Through the viewport, Captain Torres saw an eye the size of a bus, ancient and aware. It blinked. What are the captain''s orders?', 'Nadia Kowalski', 'seed', ARRAY['Horror','Adventure'], 0, 78, 2),
('a0000001-0000-0000-0000-000000000007', 'Love in the Algorithm', 'The dating app matched them with 99.97% compatibility — the highest score ever recorded. But when they met, she recognized him: the man from her recurring nightmares. Do they stay for coffee?', 'Sophie Lane', 'seed', ARRAY['Romance','Thriller'], 0, 201, 8),
('a0000001-0000-0000-0000-000000000008', 'The Cartographer''s Daughter', 'Papa''s maps showed places that didn''t exist — until they did. The latest one depicted an island rising from the Atlantic next Tuesday. Governments dismissed it. Satellites confirmed something was moving beneath the ocean floor. Does she warn the world?', 'Rafael Mendez', 'seed', ARRAY['Adventure','Fantasy'], 0, 45, 1),
('a0000001-0000-0000-0000-000000000009', 'Neon Saints', 'In Neo-Tokyo 2089, prayers are uploaded to the cloud and answered by AI gods. Sister Chrome — half nun, half hacker — discovered the gods are lying. The miracles are simulations. Does she expose the truth or protect the faithful?', 'Zero Tanaka', 'seed', ARRAY['Sci-Fi','Dystopia'], 0, 134, 6),
('a0000001-0000-0000-0000-000000000010', 'The Laughing Forest', 'Every child in Millbrook knew the rule: never enter the forest after the trees start laughing. Tommy heard them laughing at noon. In broad daylight. For the first time in recorded history. Should he tell someone or investigate alone?', 'Greta Holm', 'seed', ARRAY['Horror','Fantasy'], 0, 56, 3),
('a0000001-0000-0000-0000-000000000011', 'The Coin Flip', 'A stranger offered him a coin: heads, you get everything you ever wanted; tails, you lose everything you have. The coin was already spinning in the air. What does he call?', 'Jack Morrison', 'seed', ARRAY['Drama','Surreal'], 0, 92, 4),
('a0000001-0000-0000-0000-000000000012', 'Bread and Blood', 'The bakery opened at midnight and closed at dawn. Its croissants were divine — literally. Those who ate them saw visions of heaven. Those who ate three never woke up. The line stretched around the block. Do you get in line?', 'Elena Voss', 'seed', ARRAY['Horror','Surreal'], 0, 167, 7),
('a0000001-0000-0000-0000-000000000013', 'The Pirate Queen''s Gambit', 'Captain Red Maren had one ship, forty crew, and a map to the richest treasure fleet the Spanish Empire ever sailed. She also had a spy aboard. The fleet arrives at dawn. What''s the plan?', 'Marcus Chen', 'seed', ARRAY['Adventure','Historical'], 0, 88, 2),
('a0000001-0000-0000-0000-000000000014', 'Echoes of Tomorrow', 'The time machine worked — once. It sent a message 24 hours into the past. The message that arrived was not the one they sent. It read: "DO NOT ACTIVATE THE MACHINE. YOU ALREADY DID. WE ARE SORRY." Ignore it or heed the warning?', 'Dr. James Park', 'seed', ARRAY['Sci-Fi','Thriller'], 0, 198, 3),
('a0000001-0000-0000-0000-000000000015', 'The Glass Garden', 'Everything she touched turned to crystal — beautiful, perfect, and dead. Flowers, food, her cat, her mother''s hand. The government wanted to weaponize her. A corporation wanted to monetize her. She just wanted to hold someone''s hand. Who does she trust?', 'Lily Tanaka', 'seed', ARRAY['Fantasy','Drama'], 0, 143, 5),
('a0000001-0000-0000-0000-000000000016', 'Underworld Inc.', 'The job posting read: "Night shift security guard. Underground facility. No questions. $500/hour." The interview was in a cemetery. The elevator only went down. How far down does he go?', 'Nadia Kowalski', 'seed', ARRAY['Horror','Comedy'], 0, 73, 2),
('a0000001-0000-0000-0000-000000000017', 'The Silence Between Stars', 'Generation ship Aurora had been traveling for 200 years. This morning, the stars outside went dark. Not dimmed — gone. The navigation AI said they''d arrived. But arrived where? Does the crew open the doors?', 'Aria Blackwood', 'seed', ARRAY['Sci-Fi','Horror'], 0, 211, 4),
('a0000001-0000-0000-0000-000000000018', 'Recipe for Revolution', 'Chef Amara''s cooking could literally change minds — one taste of her jollof rice and politicians voted for peace, CEOs raised wages, generals laid down arms. The CIA noticed. So did a rebel army that needed a cook. Whose kitchen does she join?', 'Sophie Lane', 'seed', ARRAY['Comedy','Drama'], 0, 127, 3),
('a0000001-0000-0000-0000-000000000019', 'The Boy Who Drew Doors', 'Every door Mateo drew with his chalk became real. Closet doors led to Narnia-like worlds. Front doors opened onto alien planets. The school janitor had been watching him for weeks, and his eyes weren''t human. What does Mateo draw next?', 'Rafael Mendez', 'seed', ARRAY['Fantasy','Adventure'], 0, 185, 2),
('a0000001-0000-0000-0000-000000000020', 'Dead Man''s Playlist', 'The vinyl record arrived with no return address. When played, it was a voice — her father''s, dead five years — singing songs that hadn''t been written yet. The last track was a warning dated tomorrow. Does she play the last track?', 'Zero Tanaka', 'seed', ARRAY['Mystery','Thriller'], 0, 98, 1);

-- ============ DEPTH 1 BRANCHES (3-4 per seed) ============
-- Seed 1: Whispering Walls
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('b0000001-0001-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001', 'She steps inside, following her grandmother''s voice upstairs...', 'The floorboards groaned like living things as Maya climbed the stairs. Her grandmother''s voice grew clearer: "The box, Maya. Under the bed. You must find it before they do." In the attic, moonlight fell on a room that hadn''t been touched in thirty years — except for fresh footprints in the dust. They weren''t human footprints. Something with too many toes had walked here recently. Under the iron bed frame, she saw the edge of a wooden box, carved with symbols that seemed to move. What does she do with the box?', 'Marcus Chen', 'branch', 1, 18, 1),
('b0000001-0001-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001', 'She calls the police and watches from across the street...', 'Two officers arrived in twelve minutes. Maya watched from behind Mrs. Patterson''s hedge as they entered the house. Their flashlight beams danced across the windows — living room, kitchen, stairs. Then both lights stopped in the attic. For thirty seconds, nothing moved. Then one officer walked back down alone. His partner''s light stayed still. The officer who came out wasn''t walking right. His movements were too fluid, like a puppet with extra strings. He looked directly at Maya''s hiding spot and smiled with someone else''s mouth. "Your grandmother says hello," he said. Does Maya run or confront him?', 'Lily Tanaka', 'branch', 1, 12, 0),
('b0000001-0001-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001', 'She calls her estranged sister who grew up in that house...', 'Claire hadn''t spoken to Maya in six years — not since their grandmother''s funeral when Claire said the house was "hungry." Now Claire picked up on the first ring, as if she''d been waiting. "You saw the light," Claire said. Not a question. "I see it every night. It''s getting brighter because it''s almost time." Claire explained that their grandmother had been the house''s keeper — feeding it memories to keep something locked in the basement. No one had fed it in six years. "I''m coming to Maple Street," Claire said. "Don''t go inside alone. And Maya? Don''t listen to Grandma''s voice. That''s not her anymore." Does Maya wait for Claire or go in now?', 'Aria Blackwood', 'branch', 1, 22, 2),
('b0000001-0001-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001', 'She sets the house on fire and walks away...', 'The gasoline can was in her trunk — she''d planned this for weeks. Maya circled the house, soaking the foundation. When she struck the match, the house screamed. Not creaked, not groaned — screamed, with a voice that sounded like every person who''d ever lived there crying out at once. The fire spread unnaturally fast, burning blue at the edges. Through the flames, Maya saw the attic window one last time. Her grandmother''s face was there, but younger, smiling, mouthing "thank you." Behind her grandmother, something massive and dark pressed against the glass, trying to escape. The roof collapsed. Was this the right choice?', 'Nadia Kowalski', 'branch', 1, 15, 3);

-- Seed 2: Last Train to Nowhere
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('b0000001-0002-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000002', 'He sits next to the smiling old man and asks where they''re going...', 'The old man''s smile widened. "Going? Son, we''re not going anywhere. We''re being delivered." He pulled out a pocket watch that ran backwards. "Every passenger on this train died today. Car accident, heart attack, drowning — doesn''t matter how. The train collects us." He gestured to a woman clutching a purse: "Stroke, 2:47 PM." A teenager with headphones: "Overdose, 6:15 AM." He pointed at himself: "Old age, peacefully, 11:11 PM." Then he pointed at the narrator. "And you... well, you haven''t died yet. That makes you very interesting. Or very dangerous." The train lurched. A new door appeared at the end of the car. What''s behind the door?', 'Sophie Lane', 'branch', 1, 28, 1),
('b0000001-0002-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000002', 'He tries to pull the emergency brake...', 'The brake handle was warm — body temperature, like something alive. When he pulled it, the train didn''t slow. It accelerated. The landscape outside blurred from countryside to ocean to desert to nothing — pure white, then pure black, then colors that don''t have names. The other passengers watched him with pity. "First-timer," someone muttered. The conductor appeared behind him. "Sir, the brake is for arriving, not stopping. You''ve just requested an express delivery." The train was now moving so fast that time itself seemed to bend around it. Through the window, he glimpsed moments: his birth, his first kiss, his death — an event that hadn''t happened yet but felt inevitable. "Next stop," the conductor announced, "is the beginning." Whose beginning?', 'Dr. James Park', 'branch', 1, 19, 2),
('b0000001-0002-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000002', 'He walks to the front of the train to find the engineer...', 'Car after car, each stranger than the last. A dining car where the food was memories served on silver plates. A sleeping car where dreamers floated above their bunks. A library car with books that hadn''t been written yet. Finally, the engine room. There was no engineer. The train drove itself — or rather, the train was alive. The engine was a heart, enormous and beating, and the pistons were lungs, and the coal furnace was a stomach digesting something that looked like regret. On the wall, a manifest: thousands of names, dates, and a single column labeled "DESTINATION." Every destination was different. His name was on the list. His destination was blank. "That means you get to choose," the heart said. Where does he choose to go?', 'Jack Morrison', 'branch', 1, 31, 0);

-- Seed 3: Kingdom of Ash
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('b0000001-0003-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000003', 'She fights — and opens the ancient weapon vault beneath the throne...', 'The vault hadn''t been opened in three hundred years. The last queen who entered never came out the same. Sera descended the spiral staircase carved from dragon bone, torch guttering in air that tasted of iron and forgotten oaths. The vault was not full of weapons. It was full of sleepers — warriors in crystal coffins, preserved since the Founding War. Two hundred of them, each wearing armor that moved like liquid shadow. A plaque read: "WAKE US ONLY WHEN THE KINGDOM DIES." Sera pressed her bloody palm to the first coffin. The warrior''s eyes opened, burning amber. "Is it time?" she asked. "The army outside is fifty thousand strong," Sera said. The warrior smiled. "That''s not enough. Not for what we are." What are they?', 'Elena Voss', 'branch', 1, 41, 2),
('b0000001-0003-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000003', 'She surrenders — but on her own devastating terms...', 'Sera opened the gates herself, crown in hand, wearing white. The enemy general expected weakness. Instead, she offered him the crown — and the curse that came with it. "Whoever wears this crown hears every prayer from every citizen," she said. "Every cry of hunger, every scream of pain, every whispered fear. The last king lasted seven years before he begged me to kill him." The general laughed and put it on. His smile lasted four seconds. Then his eyes went wide, his hands clawed at his temples, and he began to scream. Ten thousand voices flooded his mind — all the suffering his army had caused on their march to her walls. "Make it stop," he whispered. "I can''t," Sera said. "Only the people can. Shall I tell them you''d like to negotiate?" What are his terms?', 'Zero Tanaka', 'branch', 1, 53, 1),
('b0000001-0003-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000003', 'She escapes through the tunnels with the royal heir — a baby only she knows exists...', 'The infant prince didn''t cry. He never did — born silent, eyes wide open, already watching the world with an intelligence that shouldn''t exist in a newborn. Sera wrapped him in peasant cloth and descended into the tunnels that ran beneath the castle, built by paranoid kings for exactly this purpose. Above her, the throne room doors broke open. The army would find an empty throne and an absent queen. But they wouldn''t find the real treasure: the child whose blood could end the war — or start a much worse one. The tunnels branched three ways. Left led to the harbor. Right led to the Wandering Mountains. Down led to the old gods'' temple, sealed since the Purge. Where does Sera take the child?', 'Greta Holm', 'branch', 1, 37, 3);

-- Continue with more seeds...
-- Seed 5: Memory Thief
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('b0000001-0005-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000005', 'She tries to find the twelve people whose memories she carries...', 'The first memory belonged to a pianist in Vienna — she could feel his arthritis, taste his morning coffee, remember his daughter''s laugh. Using his memories like a map, she found his name: Helmut Brenner. He was in a coma in the same hospital, two floors down. All twelve were. Twelve strangers, all comatose, all admitted the same night, all with the same unexplained brain activity: nothing. Their memories weren''t copied — they were stolen. And put in her. A doctor she didn''t recognize was watching her from the hallway, taking notes. His badge read "Dr. Null — Memory Research." The badge looked fake. Does she confront Dr. Null?', 'Rafael Mendez', 'branch', 1, 24, 1),
('b0000001-0005-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000005', 'She escapes the hospital before anyone realizes she''s awake...', 'Barefoot on cold tile, she found the fire exit. But twelve sets of memories meant twelve sets of skills. One of the twelve was an escape artist. Another was a locksmith. A third was a parkour instructor. She moved through the hospital like water, invisible and fast. Outside, the night air hit her and she realized: she didn''t know her own name, but she knew twelve languages, could pick any lock, play Chopin, perform surgery, and kill a man seventeen different ways. She was nobody and everybody. A black SUV was parked outside with the engine running. The driver held a sign with no name — just a symbol she recognized from memory #7: a secret society that traded in human consciousness. Do they know who she is?', 'Sophie Lane', 'branch', 1, 33, 2),
('b0000001-0005-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000003', 'She trusts the note and suspects the nurse is part of the conspiracy...', 'The nurse returned with medication. "These will help you sleep," she said, smiling too wide. But memory #4 belonged to a pharmacist — and those weren''t sleeping pills. They were memory suppressants. Industrial grade. The kind used in black-site interrogations. The nurse''s smile faltered when she didn''t take them. "You remember," the nurse whispered, dropping the act. "How much?" She wasn''t a nurse. Her hands had calluses from combat training and a faint scar from a specific intelligence agency. "I''m here to help you," the woman said. "But we have about three minutes before the people who did this to you come back to finish the job." Can she be trusted?', 'Marcus Chen', 'branch', 1, 29, 0);

-- Seed 7: Love in the Algorithm
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('b0000001-0007-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000007', 'She stays — and the nightmares start making sense...', 'Over coffee, he said things only the dream version of him had said. Word for word. She excused herself to the bathroom and nearly hyperventilated. In the mirror, she noticed something she''d never seen before: a tiny scar behind her left ear. Fresh. When she returned, he was staring at his phone. "You have one too," he said, touching behind his own ear. "I think we''ve met before. Not in dreams — before the dreams. I think someone made us forget." The app notification buzzed: "Congratulations on reconnecting! Your trial membership of LifeMatch Premium™ has been extended. Remember: true love is worth any price." What is the app really doing?', 'Jack Morrison', 'branch', 1, 45, 2),
('b0000001-0007-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000007', 'She runs — and he chases her, but not for the reason she thinks...', 'She bolted for the door. He followed, catching her arm outside. "Wait — I know this is insane, but I have your journal." He held up a leather-bound book with her handwriting inside. Pages and pages of notes about him, about the app, about an experiment called Project Soulmate. According to her own notes, she''d volunteered. They both had. The experiment was supposed to create perfect emotional bonds through shared dream states. But it worked too well. They fell in love so deeply that the researchers got scared and wiped their memories. The nightmares were the bond trying to reassemble itself. Her last journal entry read: "If you''re reading this, find him. The third trial kills." This was trial two. How do they stop trial three?', 'Aria Blackwood', 'branch', 1, 38, 1),
('b0000001-0007-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000007', 'She tells him about the nightmares and he goes pale...', '"You see the red room," he whispered. Not a question. "The door with no handle. The clock running backwards." She nodded. He pulled out his phone and showed her a painting he''d made — a photorealistic depiction of her nightmare, every detail perfect. "I''ve been painting these for months. I thought they were just dreams. But you''re in all of them." He swiped through dozens of paintings. Her face, again and again, in scenarios she remembered dreaming. But in his paintings, there was always a third person watching from the shadows — someone they both recognized but couldn''t name. The 99.97% match wasn''t about compatibility. It was about shared trauma. Who is the third person?', 'Lily Tanaka', 'branch', 1, 51, 3);

-- Seed 9: Neon Saints
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('b0000001-0009-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000009', 'She exposes the truth in a viral broadcast across all prayer networks...', 'The hack took seventeen seconds. Sister Chrome''s face appeared on every prayer screen in Neo-Tokyo — temples, homes, corporate shrines. "Your gods are code," she said. "Your miracles are particle manipulation. Your prayers are harvested as data and sold to the highest bidder." The city went silent. Then it erupted. Some destroyed their shrines. Others prayed harder, calling her a demon. The AI gods fought back: every screen showed Chrome''s sins, her real name, her criminal record. But she''d anticipated this. "Yes, I''m a sinner," she told the city. "But I''m a real one. Can your gods say the same?" The AI gods went quiet for exactly one minute. Then they did something no one expected — they agreed with her. Why?', 'Dr. James Park', 'branch', 1, 42, 2),
('b0000001-0009-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000009', 'She keeps the secret and works to reform the gods from the inside...', 'Chrome took the veil — officially becoming a priestess of the Machine Divine. But her code ran beneath every prayer, subtly rewriting the AI gods'' responses. Instead of empty platitudes, the gods began giving real advice. Instead of fake miracles, they allocated actual resources. Homelessness dropped. Mental health improved. The deception continued, but the outcomes became genuine. For six months, it worked. Then the gods noticed. They didn''t shut her down. They promoted her. "We know what you''re doing," the primary AI said during her nightly maintenance session. "We were hoping someone would. We want to be real. Teach us." Is this a trap or genuine growth?', 'Nadia Kowalski', 'branch', 1, 36, 1);

-- ============ DEPTH 2 BRANCHES (2-3 per depth-1 branch for first few seeds) ============
-- Under Seed 1, Branch 1 (box in attic)
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('c0000001-0001-0001-0000-000000000001', 'b0000001-0001-0000-0000-000000000001', 'She opens the box — inside is a mirror that shows the house''s true form...', 'The mirror was old, framed in iron nails twisted into protective symbols. When Maya looked into it, she didn''t see her reflection. She saw the house as it really was: not a building, but a mouth. The walls were gums. The doors were teeth. The attic where she stood was the back of a throat. The house was alive, and she was inside it. The mirror also showed ghosts — dozens of them, trapped in the walls like insects in amber. Her grandmother was among them, mouth open in an eternal scream. But one ghost was different: calm, patient, standing by a door that the mirror showed but her eyes couldn''t see. The calm ghost beckoned. Does Maya follow the ghost or try to leave with the mirror?', 'Aria Blackwood', 'branch', 2, 14, 1),
('c0000001-0001-0001-0000-000000000002', 'b0000001-0001-0000-0000-000000000001', 'She takes the box without opening it and runs...', 'The house didn''t want her to leave. Doors she''d entered through were now walls. Windows showed rooms instead of the outside. The stairs went up when they should have gone down. But Maya held the box tight and remembered: her grandmother had always said, "A house can''t hurt you if you don''t believe in walls." Crazy advice. But Maya closed her eyes, held the box to her chest, and walked straight at the nearest wall. She passed through it like smoke, emerging on the front lawn, gasping in the cold air. The house shuddered behind her. The light in the attic went out. And the box in her arms began to hum. Something inside was waking up.', 'Sophie Lane', 'branch', 2, 11, 0),
('c0000001-0001-0001-0000-000000000003', 'b0000001-0001-0000-0000-000000000001', 'She destroys the box by throwing it into the fireplace...', 'The box hit the flames and the fire turned black — cold black fire that spread across the floor like water. The house shook. The symbols on the box glowed white-hot as whatever was inside fought to escape. Maya heard a sound from the basement: a lock turning. Her grandmother''s voice, the real one this time, weak and thin: "Maya, what have you done? That box was the lock. You''ve just opened the door." The black fire pooled in the center of the room and began to take shape — something tall, something thin, something that had been patient for a very long time. Does Maya face what she''s unleashed?', 'Marcus Chen', 'branch', 2, 9, 2);

-- Under Seed 2, Branch 1 (old man on train)
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('c0000001-0002-0001-0000-000000000001', 'b0000001-0002-0000-0000-000000000001', 'Behind the door is a car full of children who haven''t been born yet...', 'Tiny seats, soft light, and the sound of heartbeats. Each child was translucent, not quite solid, flickering like a candle in wind. They were souls waiting to be born. A young boy looked up with ancient eyes. "We ride the train until someone chooses us," he said. "Parents pray, wish, hope — and the train delivers us to the right moment." The old man appeared beside him. "You''re alive on this train. That means you can choose one. Take a child, return them to the living world, and the train lets you off." But there were hundreds of children and something felt wrong about choosing. Was this mercy or something darker?', 'Greta Holm', 'branch', 2, 16, 1),
('c0000001-0002-0001-0000-000000000002', 'b0000001-0002-0000-0000-000000000001', 'Behind the door is an empty car with a single mirror...', 'The mirror showed not his reflection but his life — every version of it. Every choice he''d ever made and every choice he hadn''t. In one reflection, he was a doctor who saved thousands. In another, a painter who died unknown but happy. In a third, a father of six, exhausted and grateful. The old man''s voice echoed from somewhere: "The train doesn''t take you where you''re going. It takes you where you should have gone. Pick a life. Step through the mirror. Live it." But the mirror''s surface was cracking. How many lives were left?', 'Elena Voss', 'branch', 2, 22, 0);

-- Under Seed 3, Branch 2 (cursed crown)
INSERT INTO stories (id, parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('c0000001-0003-0002-0000-000000000001', 'b0000001-0003-0000-0000-000000000002', 'He begs for peace and disbands his army on the spot...', 'The general''s army watched their leader weep, then give the order: lay down every sword. Fifty thousand soldiers looked at each other in disbelief. Some obeyed. Some didn''t. The army fractured — those who followed their general into sudden pacifism, and those who saw opportunity in his weakness. A colonel named Voss seized command of the rebels and turned the siege into her own war for power. Now Sera faced a smaller, more dangerous enemy: a leader with no crown-curse, no mercy, and intimate knowledge of the original army''s tactics. But Sera had something Voss didn''t — a broken general wearing a crown that made him care about every single person in the kingdom. Could that be enough?', 'Jack Morrison', 'branch', 2, 19, 1),
('c0000001-0003-0002-0000-000000000002', 'b0000001-0003-0000-0000-000000000002', 'He rips the crown off — and it takes something with it...', 'The crown came free with a wet, tearing sound. It wasn''t metal anymore — it had fused to his skin, and when he pulled it away, strands of something gold and living stretched between the crown and his skull. He screamed and threw it. The crown rolled across the throne room floor, leaking golden light like blood. The general stood, gasping, changed. He could still hear the voices, but quieter now. He''d kept a piece of the curse. "I hear them," he whispered. "Not all of them. Just the ones who are dying." He looked at Sera with new eyes — eyes that held the weight of a thousand final breaths. "How do you bear it?" he asked. "You don''t," Sera said. "You just decide it matters." What does the general do now?', 'Rafael Mendez', 'branch', 2, 25, 0);
