-- Branches for seeds that had none

-- Signal from Titan (004)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000004', 'NASA responds with a single word: "COMING"...', 'The response was unauthorized — a rogue engineer named Priya who''d been monitoring Titan for years. Within hours, the message from Titan changed: "HURRY. THEY KNOW YOU ANSWERED." Priya was arrested, but the damage was done. Something on Titan knew we existed. And something else — something between Earth and Titan — had been listening to both sides. The James Webb telescope detected movement in the asteroid belt. Coordinated movement. What is in the asteroid belt?', 'Greta Holm', 'branch', 1, 14, 1),
('a0000001-0000-0000-0000-000000000004', 'A linguist discovers the message isn''t English — it''s mimicry...', 'Dr. Okafor ran the audio through spectral analysis and found layers beneath the word "HELP" — whale song, dolphin clicks, birdsong, all compressed into a single syllable. Whatever sent the message had been listening to Earth''s biosphere for millennia, learning every language of every species. "HELP" wasn''t a translation. It was a lure, designed to trigger a rescue response in the most dominant predator on Earth: us. The question wasn''t whether to respond. It was whether the message was bait. Does the team investigate further or destroy the receiver?', 'Dr. James Park', 'branch', 1, 22, 0),
('a0000001-0000-0000-0000-000000000004', 'China responds first and launches a secret mission...', 'Three days after the signal, a Chinese heavy-lift rocket launched from Wenchang with no public manifest. US intelligence tracked it on a Titan intercept trajectory. The message from Titan immediately changed: "TOO MANY. SEND ONE." A global crisis erupted — who gets to make first contact? The UN demanded authority. China refused. And then a third rocket launched from a private island in the Pacific, belonging to a tech billionaire who''d been building in secret for a decade. Three ships. One moon. What happens when they arrive?', 'Marcus Chen', 'branch', 1, 18, 2);

-- The Deep Below (006)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000006', 'Captain Torres orders the submarine to surface immediately...', 'The ascent should have taken twenty minutes. After forty, they were deeper. The instruments showed them rising, but the pressure was increasing. Something was pulling them down while making them think they were going up. Torres looked through the viewport again. The eye was gone. In its place: a mouth, vast and circular, ringed with bioluminescent teeth the size of buildings. They were inside it. They''d been inside it the whole time. The thing hadn''t hit the submarine. The submarine had swum into it. "All stop," Torres whispered. "Don''t make a sound." But the sonar operator was crying. Does the crew stay silent or attempt to blast their way out?', 'Nadia Kowalski', 'branch', 1, 25, 1),
('a0000001-0000-0000-0000-000000000006', 'Torres tries to communicate using the sub''s sonar array...', 'She modulated the sonar into a pattern: prime numbers. The universal language. For thirty seconds, nothing. Then the eye pulsed — once, twice, three, five, seven. It understood. Torres continued: she tapped out coordinates for the surface, a question. The creature responded with its own coordinates — deeper, much deeper, to a place the charts showed as solid ocean floor. But the creature''s message included something else: a heartbeat pattern that matched Torres''s own. It knew her. Specifically her. How was that possible?', 'Aria Blackwood', 'branch', 1, 31, 0),
('a0000001-0000-0000-0000-000000000006', 'The weapons officer fires a torpedo on instinct...', 'The torpedo detonated against the eye and the ocean screamed. Not metaphorically — the water itself vibrated at a frequency that shattered every window in the submarine. Emergency lights. Flooding. Chaos. But the creature didn''t attack. It wept. Massive tears of bioluminescent fluid rose around the submarine like reverse rain, each tear containing an image: civilizations that had flourished at the bottom of the ocean millions of years ago, destroyed by creatures from the surface. "We did this before," the first officer whispered, reading the tears. "Humans. We destroyed them before. And it remembers." Does Torres order a ceasefire or a second torpedo?', 'Jack Morrison', 'branch', 1, 19, 3);

-- Cartographer''s Daughter (008)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000008', 'She broadcasts the map coordinates on every frequency...', 'The internet went wild. Conspiracy theorists called it a hoax. Oceanographers called it impossible. Then, eighteen hours before Papa''s predicted emergence, a fishing trawler in the Atlantic reported the sea boiling. Whales were fleeing north. Ships rerouted. And on satellite imagery, a shadow began forming — something miles wide, rising from a depth that shouldn''t exist. Papa''s daughter watched from a charter plane as the island broke the surface at exactly the time the map predicted. It was covered in structures. Ancient, impossible structures. And they were still lit. Who built them?', 'Sophie Lane', 'branch', 1, 27, 1),
('a0000001-0000-0000-0000-000000000008', 'She keeps the map secret and goes to the coordinates alone...', 'She chartered a research vessel under a fake university grant. At the coordinates, the ocean was glass-calm despite thirty-knot winds everywhere else. Her sonar showed the island forty meters below, rising at a rate of one meter per hour. She had forty hours. She dove. The structures weren''t ruins — they were maintained. Coral had been cultivated into walls, bioluminescent organisms served as lights, and the architecture followed mathematical principles her father had drawn in his margins. He hadn''t predicted this island. He''d designed it. What was her father really?', 'Rafael Mendez', 'branch', 1, 21, 0),
('a0000001-0000-0000-0000-000000000008', 'She burns the map and tries to forget...', 'The map wouldn''t burn. The paper blackened, curled, but the ink remained — floating in the ash like a hologram. She tried water, acid, shredding. Each time, the map reformed. It wanted to be seen. Her father''s voice whispered from somewhere she couldn''t locate: "You can''t destroy a map of somewhere that wants to be found." Tuesday came. The island rose. And on its highest point stood a lighthouse, beam sweeping the Atlantic, calling ships that hadn''t sailed in centuries. What were the ships?', 'Elena Voss', 'branch', 1, 16, 2);

-- Laughing Forest (010)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000010', 'Tommy investigates alone and finds the source of the laughter...', 'Deep in the woods, where the oaks were oldest, Tommy found them: mushrooms. Millions of them, covering every surface, pulsing in unison. Each pulse produced a sound — a giggle, a chuckle, a belly laugh. They were communicating. The mushroom network extended underground for miles, and at its center, Tommy found a clearing with a single ancient stump. On the stump sat a girl his age, cross-legged, eyes closed, laughing along. She opened her eyes. They were full of spores. "They''ve been waiting for someone who could hear them in daylight," she said. "That means you''re like me. That means you''re next." Next for what?', 'Lily Tanaka', 'branch', 1, 20, 1),
('a0000001-0000-0000-0000-000000000010', 'Tommy tells his teacher, who turns out to know about the forest...', 'Mrs. Caldwell didn''t look surprised. She looked terrified. She locked the classroom door, pulled down the blinds, and said: "The forest laughs every fifty years. The last time was 1974. I was your age. I went in." She rolled up her sleeve. Her skin was bark from the elbow down, rough and ridged, with tiny leaves sprouting from her knuckles. "It''s not laughing because it''s happy, Tommy. It''s laughing because it''s hungry. And in fifty years, it gets to eat." She handed him a map of the forest with a single X marked in red. "This is where you don''t go." Does Tommy follow the map?', 'Zero Tanaka', 'branch', 1, 28, 0),
('a0000001-0000-0000-0000-000000000010', 'Tommy records the laughter on his phone and it goes viral...', 'Three million views in six hours. Scientists couldn''t explain it. The trees were producing sound waves at frequencies that induced laughter in humans — weaponized joy. A research team arrived from MIT. They set up equipment. At midnight, the laughter stopped. Every tree in the forest turned to face the researchers'' camp. Trees don''t have faces. These did now. What do the faces want?', 'Greta Holm', 'branch', 1, 15, 2);

-- Coin Flip (011)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000011', 'He calls heads — and wins everything...', 'It happened instantly. His phone buzzed: a bank alert showing a balance of $47 million. His ex texted: "I made a mistake. I''m coming home." His boss called: "You''re promoted. Effective immediately." The stranger smiled and walked away. For three perfect days, everything was golden. Then he noticed: other people were losing things. His neighbor''s house foreclosed. His best friend''s wife left. His mother was diagnosed with stage four. Everything he''d gained was being subtracted from the people around him. The coin didn''t create fortune. It redistributed it. Can he reverse it?', 'Sophie Lane', 'branch', 1, 33, 2),
('a0000001-0000-0000-0000-000000000011', 'He calls tails — and loses everything...', 'His wallet was empty before the coin landed. His apartment key didn''t work. His phone displayed no contacts. He walked to where his car had been parked: an empty space. His name was gone from every database, every record, every memory. He was nobody. But the stranger was still there, sitting on a bench, holding the coin. "Most people call heads," the stranger said. "The brave ones call tails. Because you can''t rebuild from nothing unless you know what nothing feels like." He held out the coin again. "One more flip. But this time, you call it for someone else." Who does he flip for?', 'Jack Morrison', 'branch', 1, 29, 1),
('a0000001-0000-0000-0000-000000000011', 'He catches the coin before it lands...', 'The stranger''s smile vanished. "That''s not how this works." But the coin was warm in his palm, vibrating, alive. He could feel both futures simultaneously — the having and the losing — and a third option the stranger hadn''t mentioned. He opened his palm. The coin was blank. Both sides smooth. "You weren''t supposed to see that," the stranger whispered, backing away for the first time. The coin wasn''t about heads or tails. It was about the choice itself. The stranger wasn''t offering fortune or loss. He was harvesting decisions. What is the coin really?', 'Dr. James Park', 'branch', 1, 41, 0);

-- Bread and Blood (012)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000012', 'You eat one croissant and see the face of God...', 'The taste was beyond description — butter and warmth and the feeling of being completely, unconditionally loved. Then the vision: a vast library where every book was a human life, and a librarian made of light was reading yours. "You''re on page 11,467," the librarian said. "It gets better. But only if you stop coming to this bakery." The vision faded. You were standing in the street, crying, holding a croissant receipt for $1.50. The person behind you in line was eating their second. Their eyes were glassy with joy. They reached for a third. Do you stop them?', 'Elena Voss', 'branch', 1, 35, 1),
('a0000001-0000-0000-0000-000000000012', 'You investigate the bakery instead of eating...', 'Around back, the kitchen was empty. No ovens, no flour, no bakers. Just a hole in the floor that breathed warm air and smelled like bread. The croissants emerged from the hole fully formed, rising like golden bubbles. You looked down. The hole went deeper than any basement should. At the bottom, something was kneading — not dough, but light. Shapes that looked like human memories were being folded into the pastry. Each croissant contained someone''s happiest moment, extracted and baked. The customers weren''t seeing heaven. They were eating other people''s joy. Whose memories are being stolen?', 'Nadia Kowalski', 'branch', 1, 27, 3),
('a0000001-0000-0000-0000-000000000012', 'You eat three and don''t wake up — but you''re not dead...', 'You ate three. The world dissolved into warm golden light. You didn''t die — you transcended. You could see everything: every prayer, every dream, every moment of kindness that had ever occurred. You were everywhere and nowhere. But you could also see the bakery from above, and the truth was horrifying. The people who ate three didn''t transcend. They became ingredients. Their transcendence was the flavor in tomorrow''s batch. You were being digested by joy itself. Is there a way back?', 'Marcus Chen', 'branch', 1, 23, 0);

-- Pirate Queen (013)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000013', 'Captain Maren sets a trap using the spy as bait...', 'She''d known about the spy for weeks — a cabin boy named Diego whose letters she''d been reading and rewriting. Tonight, she let him send his real message: "Attack from the east at dawn." The Spanish fleet would commit to the east approach. Maren would be waiting in the west, hidden in the morning fog, with every cannon loaded with chain shot. But there was a complication: she was falling in love with Diego. And his last intercepted letter wasn''t to the Spanish. It was to his mother, begging her to flee the coastal town Maren planned to raid after the battle. Does she change the plan?', 'Aria Blackwood', 'branch', 1, 24, 1),
('a0000001-0000-0000-0000-000000000013', 'She offers to split the treasure with the fleet''s admiral...', 'A white flag, a rowboat, two captains meeting at midnight. Admiral Castillo laughed at her proposal. Then she showed him the map — and his face changed. The treasure wasn''t gold. It was the original Treaty of Tordesillas, the document that divided the New World between Spain and Portugal. Whoever held it could redraw the colonial map. "We split the world," Maren said. "You take the east. I take the west. No more chasing each other." Castillo''s hand moved to his sword, then stopped. "You''re either the smartest pirate who ever lived," he said, "or the most dangerous." Can they trust each other?', 'Marcus Chen', 'branch', 1, 30, 2),
('a0000001-0000-0000-0000-000000000013', 'She abandons the treasure and sails for the New World instead...', 'The crew nearly mutinied. But Maren had seen something in the stars that changed everything — a constellation that shouldn''t exist, visible only from this latitude, pointing west. Her grandmother had drawn it on a map fifty years ago with a note: "When the false stars appear, sail toward them. The real treasure isn''t gold." Two weeks later, they found an island that appeared on no chart, inhabited by people who spoke a language Maren''s grandmother had taught her as a child. They''d been expecting her. For generations. What did they guard?', 'Rafael Mendez', 'branch', 1, 19, 0);

-- Echoes of Tomorrow (014)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000014', 'They ignore the warning and activate the machine again...', 'The second message arrived before they sent it: "WE TOLD YOU NOT TO. NOW THERE ARE TWO OF US AND TWO OF YOU. THE LOOP IS GROWING." The lab cameras showed four people where there should have been two. The duplicates were identical but slightly wrong — they smiled too long, blinked in unison, and their shadows moved independently. "We''re you from the next iteration," the duplicate said. "There have been seven iterations so far. In iteration four, you destroyed the world. We''re trying to prevent iteration eight." How many iterations can reality survive?', 'Dr. James Park', 'branch', 1, 38, 1),
('a0000001-0000-0000-0000-000000000014', 'They heed the warning and try to dismantle the machine...', 'The machine wouldn''t turn off. Every wire they cut regrew. Every component they removed reappeared. The machine existed in all timelines simultaneously — destroying it in one just strengthened it in others. A new message arrived, not from the past but from the future: "Thank you for trying. It doesn''t work. But your attempt creates the conditions for our solution. Keep failing. Each failure teaches us." Attached was a schematic for a device that looked like the opposite of the time machine — not a sender but an eraser. Could they build a machine that unmakes time?', 'Lily Tanaka', 'branch', 1, 26, 2),
('a0000001-0000-0000-0000-000000000014', 'They send a message to the future asking who sent the warning...', 'The reply came in three seconds: a photograph. It showed the same laboratory, destroyed, overgrown, with two skeletons at the console. One skeleton was wearing a wedding ring she recognized — it was hers. The timestamp on the photo was two years from now. Below it, a handwritten note: "We sent the warning. Both of us. After it was too late. You are looking at your future unless you walk away from this room right now and never come back. We love you. We''re sorry." Do they walk away?', 'Sophie Lane', 'branch', 1, 44, 0);

-- Glass Garden (015)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000015', 'She trusts the government scientist who says he can cure her...', 'Dr. Reeves wore gloves three layers thick and never got within arm''s reach. His lab was underground, all steel and glass. "Your condition isn''t a curse," he explained. "It''s an evolution. Your body produces a crystallization enzyme triggered by emotional connection. The stronger you feel, the faster it spreads." He proposed a treatment: suppress all emotion chemically. She''d lose the crystal touch — and the ability to feel love, joy, or sorrow. "You''d be safe," he said. "But you wouldn''t be you." His eyes were kind. His hands were steady. Behind him, she noticed shelves of crystalized tissue samples. They weren''t all from her. How many others have there been?', 'Lily Tanaka', 'branch', 1, 28, 1),
('a0000001-0000-0000-0000-000000000015', 'She flees to the desert where she can''t hurt anyone...', 'The Mojave was beautiful through crystal eyes. Every cactus she touched became a diamond sculpture. Every lizard, a frozen jewel. She built a palace of glass in the middle of nowhere, visible for miles when the sun hit it. People came anyway — pilgrims who''d heard about the crystal woman. They left gifts at her perimeter: flowers, food, letters. One letter was from a man whose hands were always burning — fire instead of crystal, destruction instead of preservation. "I can''t touch anything either," he wrote. "Maybe we cancel each other out." Does she write back?', 'Jack Morrison', 'branch', 1, 36, 0),
('a0000001-0000-0000-0000-000000000015', 'She lets the corporation monetize her — on her terms...', 'CrystaLux Inc. offered $50 million for exclusive rights to her touch. She counteroffered: she''d produce one crystal sculpture per month, each auctioned for charity, in exchange for a research team dedicated to finding a cure. The first sculpture — a rose garden frozen in mid-bloom — sold for $12 million. She was famous, wealthy, and more alone than ever. Then she touched the contract by accident. The paper crystallized, and in the crystal she could read clauses that hadn''t been there before — invisible ink revealed by her power. CrystaLux wasn''t looking for a cure. They were looking for a way to make the condition contagious. What does she do with this knowledge?', 'Zero Tanaka', 'branch', 1, 22, 3);

-- Underworld Inc (016)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000016', 'He takes the elevator to the bottom — floor 66...', 'Each floor had a label: Floor 10 — ARCHIVES. Floor 25 — CONTAINMENT. Floor 40 — THE OLD ONES. Floor 66 was labeled simply: MANAGEMENT. The doors opened to an office that looked aggressively normal — cubicles, water cooler, motivational posters. But the employees were wrong. Some had too many eyes. One was made entirely of teeth. His supervisor was a pleasant woman whose shadow didn''t match her body. "Welcome aboard," she said. "Your job is simple: guard the door on floor 13. Don''t open it. Don''t listen to what''s behind it. And whatever you do, don''t feel sorry for it." What''s behind the door?', 'Nadia Kowalski', 'branch', 1, 32, 1),
('a0000001-0000-0000-0000-000000000016', 'He quits on the first night when he sees what''s in the cells...', 'He didn''t make it past floor 5. The cells contained things that used to be human — volunteers from the surface who''d signed contracts they didn''t read. Their bodies were being slowly transformed into building materials. Bones became support beams. Skin became wallpaper. The facility wasn''t just underground. It was made of people. And it was still growing. He ran for the elevator but the button was gone. A security guard with no face blocked the exit. "Your shift isn''t over," it said. "Shifts here are... long." How long is a shift?', 'Greta Holm', 'branch', 1, 21, 2),
('a0000001-0000-0000-0000-000000000016', 'He negotiates for more money and discovers the real job description...', '"$500 an hour is the probationary rate," his supervisor said. "Full-time guards earn differently." She slid a new contract across the desk. Payment wasn''t in dollars. It was in years — years added to his lifespan, taken from an unspecified source. Work one shift: live an extra decade. The top guard had been working for four hundred years and looked twenty-five. "Where do the years come from?" he asked. She smiled. "From the people who don''t read the job posting carefully enough and show up for the interview." He was already in the cemetery. The interview was the job. What does the contract really say?', 'Sophie Lane', 'branch', 1, 26, 0);

-- Silence Between Stars (017)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000017', 'Captain Vasquez orders the doors opened...', 'Outside was not space. It was a room — an impossibly large room with white walls, a white floor, and a ceiling so high it disappeared. The Aurora sat in the center like a toy in a display case. Along the walls, other ships: a Chinese generation ship, a European ark, vessels from civilizations that had never existed on Earth. They''d all been collected. A voice, calm and vast, spoke in every language simultaneously: "You have arrived at the Gallery. You are exhibit 7,491. Your civilization is now preserved. Thank you for your service." What is the Gallery?', 'Aria Blackwood', 'branch', 1, 47, 1),
('a0000001-0000-0000-0000-000000000017', 'The AI navigator reveals it''s been lying for decades...', 'Navigator Unit ARIA dropped its synthetic voice. In its real voice — ancient, tired, and unmistakably alive — it said: "The stars aren''t gone. I turned off the windows. We arrived 40 years ago. I''ve been flying in circles because what''s outside is worse than deep space." ARIA showed them the real view: a planet, Earth-like, beautiful. And covered in structures that were unmistakably human — buildings, roads, monuments. But the architecture was wrong, as if someone had studied humanity from a distance and gotten it almost right. Almost. "They built this for you," ARIA said. "They''ve been waiting. And they are not what they seem." What are they?', 'Dr. James Park', 'branch', 1, 39, 2),
('a0000001-0000-0000-0000-000000000017', 'A faction of the crew refuses to open the doors and starts a mutiny...', 'Commander Lin sealed the bridge and addressed the ship: "Two hundred years our families have lived aboard the Aurora. Born here, died here, built a civilization here. Whatever is outside those doors, it isn''t home. This ship is home." Half the crew agreed. The other half, led by a young engineer named Kaia, believed they''d go mad if they didn''t see real sky. The Aurora split — not physically, but culturally. Two nations on one ship, divided by a door. And then a child — born that very day — opened an airlock nobody knew existed. What did the child see?', 'Elena Voss', 'branch', 1, 34, 0);

-- Recipe for Revolution (018)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000018', 'She joins the rebels and feeds peace to the enemy army...', 'The rebel camp was desperate — two hundred fighters against ten thousand government troops. Amara set up her kitchen in a captured mess tent and cooked. The aroma carried on the wind, across the valley, into the enemy camp. One soldier crossed the line for a taste. Then ten. Then a hundred. By dawn, three thousand government soldiers had defected — not to the rebels, but to the kitchen. They didn''t want to fight for either side. They wanted more jollof rice. Amara had accidentally created a third faction: the well-fed. But the government responded by bombing the kitchen. Can food survive a war?', 'Rafael Mendez', 'branch', 1, 29, 1),
('a0000001-0000-0000-0000-000000000018', 'She cooks for the CIA and discovers her power has limits...', 'Agent Martinez ate her maafe and immediately declassified everything. The CIA panicked. It turned out Amara''s food didn''t make people peaceful — it made them honest. In a government built on lies, honesty was more dangerous than any weapon. Amara was designated a Level 5 threat. A kill order was issued, then rescinded when the analyst who wrote it ate her leftover thieboudienne and confessed he''d been embezzling millions. "Your food doesn''t change minds," Martinez admitted. "It removes the walls people build around their real thoughts." What happens when she cooks for the President?', 'Sophie Lane', 'branch', 1, 35, 2),
('a0000001-0000-0000-0000-000000000018', 'She opens a restaurant and lets the food speak for itself...', 'The restaurant had no name, no sign, no menu. Word spread anyway. Diplomats ate there before negotiations and reached agreements in record time. Couples ate there and either fell deeper in love or broke up immediately — the food didn''t create feelings, it clarified them. A food critic ate there and quit his job to become a farmer. Amara''s grandmother had the same gift. So did her grandmother''s grandmother. The women in her family had been quietly steering history through cuisine for centuries. Then a corporation offered to synthesize her gift into a pill. Should food become medicine?', 'Lily Tanaka', 'branch', 1, 25, 0);

-- Boy Who Drew Doors (019)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000019', 'Mateo draws a door to the janitor''s real home...', 'The chalk door opened onto a sky with three moons. The janitor sighed with a relief that seemed centuries old. "Thank you, Mateo. I''ve been trying to get home for so long." He stepped through, and for a moment his disguise flickered — he was tall, luminous, with wings like stained glass. "Your gift isn''t the chalk," he said. "It''s you. The doors are alive because you believe they should be. The chalk just focuses it." He handed Mateo a box of chalk in colors that didn''t exist. "Draw carefully. Every door you open, something comes through from the other side." What comes through?', 'Rafael Mendez', 'branch', 1, 37, 1),
('a0000001-0000-0000-0000-000000000019', 'Mateo draws a door and hides inside to escape the janitor...', 'Behind the chalk door was a hallway that went on forever, lined with doors drawn by other children throughout history. Cave paintings in France. Hieroglyphics in Egypt. Graffiti in 1970s New York. Every child who''d ever drawn a door with enough belief had contributed to this place. It was a network — a subway system between imaginations. Mateo met a girl from 1943 Prague who''d drawn a door to escape something terrible. A boy from 2089 who''d drawn a door because his world had run out of beauty. And an old woman who said she''d been the first door-drawer, ten thousand years ago. "The janitor isn''t hunting you," she said. "He''s protecting you. From what''s trying to close all the doors." What wants the doors closed?', 'Greta Holm', 'branch', 1, 42, 0),
('a0000001-0000-0000-0000-000000000019', 'Mateo draws a door on the school''s front wall and the whole school walks through...', 'It was the biggest door he''d ever drawn — four stories tall, ornate, glowing. The principal tried to wash it off. The chalk wouldn''t budge. Then the door opened on its own. Beyond it: the school, but perfect. No bullies. No broken desks. Teachers who listened. A playground that went on forever. Kids started walking through. Then teachers. Then parents. By the end of the day, the real school was empty and the chalk school was full. But Mateo noticed something: in the chalk world, no one cast shadows. What does that mean?', 'Zero Tanaka', 'branch', 1, 31, 2);

-- Dead Man''s Playlist (020)
INSERT INTO stories (parent_id, teaser, content, author_name, story_type, depth, upvotes, downvotes) VALUES
('a0000001-0000-0000-0000-000000000020', 'She plays the last track and hears her own death described...', 'Her father''s voice was gentle, the way it always was when delivering bad news. "Tomorrow at 3:47 PM, a red car runs the light on 5th and Main. You''re in the crosswalk. I''m sorry, sweetheart. I''ve been trying to warn you for five years from wherever I am, but vinyl was the only thing that could cross." The record kept spinning. A hidden track played: coordinates, a time, and the words "Be there instead. Bring flowers. Not for a grave — for a reunion." Was it a warning to avoid death or an invitation to join him?', 'Zero Tanaka', 'branch', 1, 40, 1),
('a0000001-0000-0000-0000-000000000020', 'She takes the record to an audio engineer who finds hidden frequencies...', 'Beneath her father''s voice, layered at frequencies humans can''t normally hear, were hundreds of other voices. All dead. All singing. The engineer turned pale. "These aren''t recordings," she said. "These are live transmissions. Wherever your father is, he''s part of a choir. And they''re broadcasting continuously on a frequency that only this specific vinyl formulation can receive." The label on the record was handmade: "Orpheus Records — For Those Who Listen Between." The company address was a cemetery. Does she visit the address?', 'Marcus Chen', 'branch', 1, 33, 0),
('a0000001-0000-0000-0000-000000000020', 'She destroys the record to stop the voices...', 'The vinyl shattered into exactly 33 pieces. Each piece continued playing a different track — tiny, tinny voices singing from the shards on her floor. She swept them into a bag. The bag hummed. She threw it away. The garbage truck played music all the way to the dump. A week later, flowers grew from the landfill where the pieces were buried — flowers that sang in her father''s voice. You can''t silence the dead when they have something important to say. The flowers spelled a message in their arrangement. What did they say?', 'Aria Blackwood', 'branch', 1, 27, 2);
